version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    target-branch: "main"

  - package-ecosystem: "terraform"
    directory: "/tofu/envs/lab"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    target-branch: "main"
